#!/bin/sh

project_agent_role_is_safe() { case "$1" in manager|graph|graphiste|developer|reviewer) return 0;; *) return 1;; esac; }
project_agent_model_role_is_valid() { case "$1" in default|planner|coder|reviewer) return 0;; *) return 1;; esac; }
project_agent_access_is_valid() { case "$1" in read-only|write) return 0;; *) return 1;; esac; }
project_agent_description_is_valid() {
  value=$1
  [ -n "$value" ] && [ "${#value}" -le 160 ] || return 1
  case "$value" in *'$('*|*'`'*|*';'*|*'|'*|*'&'*|*'<'*|*'>'*|*'\\'*|*"	"*) return 1;; esac
}
project_agents_default_content() {
  cat <<'EOF'
CCB_AGENTS_VERSION=1
CCB_AGENT_ROLES=manager,graph,graphiste,developer,reviewer
CCB_AGENT_DEFAULT=manager
CCB_AGENT_MANAGER_MODEL_ROLE=planner
CCB_AGENT_MANAGER_ACCESS=read-only
CCB_AGENT_MANAGER_DESCRIPTION=Coordinate project analysis and delegation
CCB_AGENT_GRAPH_MODEL_ROLE=planner
CCB_AGENT_GRAPH_ACCESS=read-only
CCB_AGENT_GRAPH_DESCRIPTION=Analyze architecture and dependency flow
CCB_AGENT_GRAPHISTE_MODEL_ROLE=coder
CCB_AGENT_GRAPHISTE_ACCESS=write
CCB_AGENT_GRAPHISTE_DESCRIPTION=Prepare visual and interface implementation guidance
CCB_AGENT_DEVELOPER_MODEL_ROLE=coder
CCB_AGENT_DEVELOPER_ACCESS=write
CCB_AGENT_DEVELOPER_DESCRIPTION=Implement validated project changes
CCB_AGENT_REVIEWER_MODEL_ROLE=reviewer
CCB_AGENT_REVIEWER_ACCESS=read-only
CCB_AGENT_REVIEWER_DESCRIPTION=Review changes and verification evidence
EOF
}
project_agents_parse() {
  PROJECT_AGENTS_VERSION= PROJECT_AGENT_ROLES= PROJECT_AGENT_DEFAULT=
  PROJECT_AGENT_MANAGER_MODEL_ROLE= PROJECT_AGENT_MANAGER_ACCESS= PROJECT_AGENT_MANAGER_DESCRIPTION=
  PROJECT_AGENT_GRAPH_MODEL_ROLE= PROJECT_AGENT_GRAPH_ACCESS= PROJECT_AGENT_GRAPH_DESCRIPTION=
  PROJECT_AGENT_GRAPHISTE_MODEL_ROLE= PROJECT_AGENT_GRAPHISTE_ACCESS= PROJECT_AGENT_GRAPHISTE_DESCRIPTION=
  PROJECT_AGENT_DEVELOPER_MODEL_ROLE= PROJECT_AGENT_DEVELOPER_ACCESS= PROJECT_AGENT_DEVELOPER_DESCRIPTION=
  PROJECT_AGENT_REVIEWER_MODEL_ROLE= PROJECT_AGENT_REVIEWER_ACCESS= PROJECT_AGENT_REVIEWER_DESCRIPTION=
  agents_file=$1; [ -f "$agents_file" ] && [ ! -L "$agents_file" ] || return 1
  seen=' '
  while IFS= read -r line || [ -n "$line" ]; do
    case "$line" in
      CCB_AGENTS_VERSION=*|CCB_AGENT_ROLES=*|CCB_AGENT_DEFAULT=*|CCB_AGENT_MANAGER_MODEL_ROLE=*|CCB_AGENT_MANAGER_ACCESS=*|CCB_AGENT_MANAGER_DESCRIPTION=*|CCB_AGENT_GRAPH_MODEL_ROLE=*|CCB_AGENT_GRAPH_ACCESS=*|CCB_AGENT_GRAPH_DESCRIPTION=*|CCB_AGENT_GRAPHISTE_MODEL_ROLE=*|CCB_AGENT_GRAPHISTE_ACCESS=*|CCB_AGENT_GRAPHISTE_DESCRIPTION=*|CCB_AGENT_DEVELOPER_MODEL_ROLE=*|CCB_AGENT_DEVELOPER_ACCESS=*|CCB_AGENT_DEVELOPER_DESCRIPTION=*|CCB_AGENT_REVIEWER_MODEL_ROLE=*|CCB_AGENT_REVIEWER_ACCESS=*|CCB_AGENT_REVIEWER_DESCRIPTION=*) key=${line%%=*}; value=${line#*=};; *) return 1;;
    esac
    case "$seen" in *" $key "*) return 1;; *) seen="$seen$key ";; esac
    case "$key" in
      CCB_AGENTS_VERSION) PROJECT_AGENTS_VERSION=$value;; CCB_AGENT_ROLES) PROJECT_AGENT_ROLES=$value;; CCB_AGENT_DEFAULT) PROJECT_AGENT_DEFAULT=$value;;
      CCB_AGENT_MANAGER_MODEL_ROLE) PROJECT_AGENT_MANAGER_MODEL_ROLE=$value;; CCB_AGENT_MANAGER_ACCESS) PROJECT_AGENT_MANAGER_ACCESS=$value;; CCB_AGENT_MANAGER_DESCRIPTION) PROJECT_AGENT_MANAGER_DESCRIPTION=$value;;
      CCB_AGENT_GRAPH_MODEL_ROLE) PROJECT_AGENT_GRAPH_MODEL_ROLE=$value;; CCB_AGENT_GRAPH_ACCESS) PROJECT_AGENT_GRAPH_ACCESS=$value;; CCB_AGENT_GRAPH_DESCRIPTION) PROJECT_AGENT_GRAPH_DESCRIPTION=$value;;
      CCB_AGENT_GRAPHISTE_MODEL_ROLE) PROJECT_AGENT_GRAPHISTE_MODEL_ROLE=$value;; CCB_AGENT_GRAPHISTE_ACCESS) PROJECT_AGENT_GRAPHISTE_ACCESS=$value;; CCB_AGENT_GRAPHISTE_DESCRIPTION) PROJECT_AGENT_GRAPHISTE_DESCRIPTION=$value;;
      CCB_AGENT_DEVELOPER_MODEL_ROLE) PROJECT_AGENT_DEVELOPER_MODEL_ROLE=$value;; CCB_AGENT_DEVELOPER_ACCESS) PROJECT_AGENT_DEVELOPER_ACCESS=$value;; CCB_AGENT_DEVELOPER_DESCRIPTION) PROJECT_AGENT_DEVELOPER_DESCRIPTION=$value;;
      CCB_AGENT_REVIEWER_MODEL_ROLE) PROJECT_AGENT_REVIEWER_MODEL_ROLE=$value;; CCB_AGENT_REVIEWER_ACCESS) PROJECT_AGENT_REVIEWER_ACCESS=$value;; CCB_AGENT_REVIEWER_DESCRIPTION) PROJECT_AGENT_REVIEWER_DESCRIPTION=$value;;
    esac
  done <"$agents_file"
  [ "$PROJECT_AGENTS_VERSION" = 1 ] || return 1
  [ "$PROJECT_AGENT_ROLES" = manager,graph,graphiste,developer,reviewer ] || return 1
  project_agent_role_is_safe "$PROJECT_AGENT_DEFAULT" || return 1
  case ",$PROJECT_AGENT_ROLES," in *,"$PROJECT_AGENT_DEFAULT",*) :;; *) return 1;; esac
  for role in manager graph graphiste developer reviewer; do
    case "$role" in
      manager) model=$PROJECT_AGENT_MANAGER_MODEL_ROLE; access=$PROJECT_AGENT_MANAGER_ACCESS; description=$PROJECT_AGENT_MANAGER_DESCRIPTION;;
      graph) model=$PROJECT_AGENT_GRAPH_MODEL_ROLE; access=$PROJECT_AGENT_GRAPH_ACCESS; description=$PROJECT_AGENT_GRAPH_DESCRIPTION;;
      graphiste) model=$PROJECT_AGENT_GRAPHISTE_MODEL_ROLE; access=$PROJECT_AGENT_GRAPHISTE_ACCESS; description=$PROJECT_AGENT_GRAPHISTE_DESCRIPTION;;
      developer) model=$PROJECT_AGENT_DEVELOPER_MODEL_ROLE; access=$PROJECT_AGENT_DEVELOPER_ACCESS; description=$PROJECT_AGENT_DEVELOPER_DESCRIPTION;;
      reviewer) model=$PROJECT_AGENT_REVIEWER_MODEL_ROLE; access=$PROJECT_AGENT_REVIEWER_ACCESS; description=$PROJECT_AGENT_REVIEWER_DESCRIPTION;;
    esac
    project_agent_model_role_is_valid "$model" && project_agent_access_is_valid "$access" && project_agent_description_is_valid "$description" || return 1
  done
}
project_agent_details() {
  case "$1" in
    manager) PROJECT_AGENT_MODEL_ROLE=$PROJECT_AGENT_MANAGER_MODEL_ROLE; PROJECT_AGENT_ACCESS=$PROJECT_AGENT_MANAGER_ACCESS; PROJECT_AGENT_DESCRIPTION=$PROJECT_AGENT_MANAGER_DESCRIPTION;;
    graph) PROJECT_AGENT_MODEL_ROLE=$PROJECT_AGENT_GRAPH_MODEL_ROLE; PROJECT_AGENT_ACCESS=$PROJECT_AGENT_GRAPH_ACCESS; PROJECT_AGENT_DESCRIPTION=$PROJECT_AGENT_GRAPH_DESCRIPTION;;
    graphiste) PROJECT_AGENT_MODEL_ROLE=$PROJECT_AGENT_GRAPHISTE_MODEL_ROLE; PROJECT_AGENT_ACCESS=$PROJECT_AGENT_GRAPHISTE_ACCESS; PROJECT_AGENT_DESCRIPTION=$PROJECT_AGENT_GRAPHISTE_DESCRIPTION;;
    developer) PROJECT_AGENT_MODEL_ROLE=$PROJECT_AGENT_DEVELOPER_MODEL_ROLE; PROJECT_AGENT_ACCESS=$PROJECT_AGENT_DEVELOPER_ACCESS; PROJECT_AGENT_DESCRIPTION=$PROJECT_AGENT_DEVELOPER_DESCRIPTION;;
    reviewer) PROJECT_AGENT_MODEL_ROLE=$PROJECT_AGENT_REVIEWER_MODEL_ROLE; PROJECT_AGENT_ACCESS=$PROJECT_AGENT_REVIEWER_ACCESS; PROJECT_AGENT_DESCRIPTION=$PROJECT_AGENT_REVIEWER_DESCRIPTION;;
    *) return 1;;
  esac
}
project_agent_model_value() { case "$1" in default) printf '%s\n' "$PROJECT_MODEL_DEFAULT";; planner) printf '%s\n' "$PROJECT_MODEL_PLANNER";; coder) printf '%s\n' "$PROJECT_MODEL_CODER";; reviewer) printf '%s\n' "$PROJECT_MODEL_REVIEWER";; *) return 1;; esac; }
