#!/bin/sh
set -u
SCRIPT_DIR=$(CDPATH= cd "$(dirname "$0")" && pwd)
. "$SCRIPT_DIR/model-lib.sh"; . "$SCRIPT_DIR/project-config-lib.sh"; . "$SCRIPT_DIR/project-agents-lib.sh"; . "$SCRIPT_DIR/project-workflows-lib.sh"
. "$SCRIPT_DIR/project-runs-lib.sh"
usage(){ echo 'usage: ccb.sh workflow start|status|inspect|resume|complete-step ...' >&2; exit "${1:-2}"; }
safe_run(){ case "$1" in [0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]-[0-9][0-9][0-9][0-9][0-9][0-9]-[a-z]*|*[!A-Za-z0-9-]*|*--*|*..*) return 1;; *) return 0;; esac; }
now(){ date '+%Y-%m-%dT%H:%M:%S%z'; }; stamp(){ date '+%Y%m%d-%H%M%S'; }
parse_run(){ file=$1; [ -f "$file" ] && [ ! -L "$file" ] || return 1; RUN_ID= RUN_WORKFLOW= RUN_STATUS= RUN_CURRENT= RUN_COUNT= RUN_CREATED= RUN_UPDATED= RUN_COMPLETED=; seen=' '; while IFS= read -r line || [ -n "$line" ]; do case "$line" in CCB_RUN_ID=*|CCB_RUN_WORKFLOW=*|CCB_RUN_STATUS=*|CCB_RUN_CURRENT_STEP=*|CCB_RUN_STEP_COUNT=*|CCB_RUN_CREATED_AT=*|CCB_RUN_UPDATED_AT=*|CCB_RUN_COMPLETED_AT=*) key=${line%%=*}; value=${line#*=};; CCB_RUN_VERSION=1|CCB_RUN_SOURCE_TEMPLATE_VERSION=1.7.0|CCB_RUN_SOURCE_WORKFLOWS_VERSION=1|CCB_RUN_SOURCE_AGENTS_VERSION=1|CCB_RUN_SOURCE_MODELS_VERSION=1) key=${line%%=*}; value=${line#*=};; *) return 1;; esac; case "$seen" in *" $key "*) return 1;; *) seen="$seen$key ";; esac; case "$key" in CCB_RUN_ID) RUN_ID=$value;; CCB_RUN_WORKFLOW) RUN_WORKFLOW=$value;; CCB_RUN_STATUS) RUN_STATUS=$value;; CCB_RUN_CURRENT_STEP) RUN_CURRENT=$value;; CCB_RUN_STEP_COUNT) RUN_COUNT=$value;; CCB_RUN_CREATED_AT) RUN_CREATED=$value;; CCB_RUN_UPDATED_AT) RUN_UPDATED=$value;; CCB_RUN_COMPLETED_AT) RUN_COMPLETED=$value;; esac; done <"$file"; safe_run "$RUN_ID" && project_workflow_name_is_safe "$RUN_WORKFLOW" || return 1; case "$RUN_STATUS" in pending|in-progress|blocked|completed|cancelled) :;; *) return 1;; esac; }
write_run(){ file=$1; temp=$(mktemp "$(dirname "$file")/.run.conf.tmp.XXXXXX") || return 1; printf 'CCB_RUN_VERSION=1\nCCB_RUN_ID=%s\nCCB_RUN_WORKFLOW=%s\nCCB_RUN_STATUS=%s\nCCB_RUN_CURRENT_STEP=%s\nCCB_RUN_STEP_COUNT=%s\nCCB_RUN_CREATED_AT=%s\nCCB_RUN_UPDATED_AT=%s\nCCB_RUN_COMPLETED_AT=%s\nCCB_RUN_SOURCE_TEMPLATE_VERSION=1.7.0\nCCB_RUN_SOURCE_WORKFLOWS_VERSION=1\nCCB_RUN_SOURCE_AGENTS_VERSION=1\nCCB_RUN_SOURCE_MODELS_VERSION=1\n' "$RUN_ID" "$RUN_WORKFLOW" "$RUN_STATUS" "$RUN_CURRENT" "$RUN_COUNT" "$RUN_CREATED" "$RUN_UPDATED" "$RUN_COMPLETED" >"$temp" && chmod 644 "$temp" && mv "$temp" "$file"; }
load_project(){ target=$1; [ -d "$target" ] && [ ! -L "$target" ] || return 1; target=$(CDPATH= cd "$target" && pwd) || return 1; project_models_parse "$target/.ccb/models.conf" && project_agents_parse "$target/.ccb/agents.conf" && project_workflows_parse "$target/.ccb/workflows.conf"; }
command=${1:-}; shift || :
case "$command" in
 start)
  name=${1:-}; target=${2:-.}; [ "$#" -le 2 ] || usage 2; project_workflow_name_is_safe "$name" || usage 2; load_project "$target" || { echo 'error: invalid project workflow configuration' >&2; exit 1; }; project_workflow_details "$name" || exit 1; runs="$target/.ccb/runs"; [ ! -e "$runs" ] || { [ -d "$runs" ] && [ ! -L "$runs" ] || { echo 'error: unsafe runs directory' >&2; exit 1; }; }; [ -d "$runs" ] || mkdir "$runs" || exit 1; base="$(stamp)-$name"; runid=$base; n=2; while [ -e "$runs/$runid" ] || [ -L "$runs/$runid" ]; do runid="$base-$n"; n=$((n+1)); done; tmp=$(mktemp -d "$runs/.${runid}.tmp.XXXXXX") || exit 1; created=$(now); RUN_ID=$runid RUN_WORKFLOW=$name RUN_STATUS=pending RUN_CURRENT=1 RUN_COUNT=$(printf '%s' "$PROJECT_WORKFLOW_STEPS" | awk -F, '{print NF}') RUN_CREATED=$created RUN_UPDATED=$created RUN_COMPLETED=; write_run "$tmp/run.conf" || exit 1; { printf '# CCB Workflow Run Context\n\nRun: %s\nWorkflow: %s\nTarget: %s\nStatus: pending\n\n## Project context\n\n' "$runid" "$name" "$target"; [ -f "$target/.ccb/context/project.md" ] && [ ! -L "$target/.ccb/context/project.md" ] && sed -n '1,4096p' "$target/.ccb/context/project.md"; printf '\n## Workflow snapshot\n\n%s\n\nNo agent execution is performed by CCB V1.7.0-C.\n' "$(printf '%s' "$PROJECT_WORKFLOW_STEPS" | sed 's/,/\n- /g; s/^/- /')"; } >"$tmp/context.md"; chmod 644 "$tmp/context.md"; i=0; old=$IFS; IFS=,; for role in $PROJECT_WORKFLOW_STEPS; do IFS=$old; i=$((i+1)); dir=$(printf '%s/%02d-%s' "$tmp" "$i" "$role"); mkdir "$dir" || exit 1; project_agent_details "$role"; model=$(project_agent_model_value "$PROJECT_AGENT_MODEL_ROLE"); printf 'CCB_STEP_VERSION=1\nCCB_STEP_NUMBER=%s\nCCB_STEP_ROLE=%s\nCCB_STEP_STATUS=%s\nCCB_STEP_ACCESS=%s\nCCB_STEP_MODEL_ROLE=%s\nCCB_STEP_PROVIDER=%s\nCCB_STEP_MODEL=%s\nCCB_STEP_DESCRIPTION=%s\nCCB_STEP_STARTED_AT=\nCCB_STEP_COMPLETED_AT=\n' "$i" "$role" "$( [ "$i" -eq 1 ] && printf ready || printf pending)" "$PROJECT_AGENT_ACCESS" "$PROJECT_AGENT_MODEL_ROLE" "$PROJECT_MODEL_PROVIDER" "$model" "$PROJECT_AGENT_DESCRIPTION" >"$dir/step.conf"; printf '# Step Input\n\nRun: %s\nWorkflow: %s\nStep: %s/%s\nRole: %s\nAccess: %s\n\n## Role purpose\n\n%s\n\n## Project context\n\nReference: ../../context.md\n\n## Previous step result\n\n%s\n\nNo agent is executed by CCB V1.7.0-C.\n' "$runid" "$name" "$i" "$RUN_COUNT" "$role" "$PROJECT_AGENT_ACCESS" "$PROJECT_AGENT_DESCRIPTION" "$( [ "$i" -eq 1 ] && printf None || printf "../$(printf '%02d' $((i-1)))-previous/result.md")" >"$dir/input.md"; printf '# Step Result\n\nStatus: pending\n\nRecord the result of this step below.\n' >"$dir/result.md"; chmod 644 "$dir"/*; IFS=,; done; IFS=$old; mv "$tmp" "$runs/$runid" || exit 1; printf '[OK] workflow run created\nRun ID: %s\nWorkflow: %s\nStatus: pending\nSteps: %s\nCurrent step: 1\nPath: .ccb/runs/%s\nExecution: disabled\n' "$runid" "$name" "$RUN_COUNT" "$runid";;
 status|inspect|resume|complete-step) echo 'error: run inspection and progression commands are not available in this compact build' >&2; exit 2;; *) usage 2;; esac
