#!/bin/sh

project_models_parse() {
  models_conf_parse "$1" || return 1
  PROJECT_MODEL_FORMAT=$MODEL_CONF_FORMAT; PROJECT_MODEL_PROVIDER=$MODEL_CONF_PROVIDER
  PROJECT_MODEL_MODE=$MODEL_CONF_MODE; PROJECT_MODEL_HOST=$MODEL_CONF_HOST; PROJECT_MODEL_PRESET=$MODEL_CONF_PRESET
  PROJECT_MODEL_DEFAULT=$MODEL_CONF_DEFAULT; PROJECT_MODEL_PLANNER=$MODEL_CONF_PLANNER; PROJECT_MODEL_CODER=$MODEL_CONF_CODER
  PROJECT_MODEL_MANAGER=$MODEL_CONF_MANAGER; PROJECT_MODEL_GRAPH=$MODEL_CONF_GRAPH; PROJECT_MODEL_GRAPHISTE=$MODEL_CONF_GRAPHISTE
  PROJECT_MODEL_DEVELOPER=$MODEL_CONF_DEVELOPER; PROJECT_MODEL_REVIEWER=$MODEL_CONF_REVIEWER; PROJECT_MODEL_FALLBACK=$MODEL_CONF_FALLBACK
}

project_conf_parse() {
  PROJECT_NAME= PROJECT_PROFILE=
  project_file=$1
  [ -f "$project_file" ] && [ ! -L "$project_file" ] || return 1
  seen=' '
  while IFS= read -r line || [ -n "$line" ]; do
    case "$line" in CCB_PROJECT_NAME=*|CCB_PROJECT_PROFILE=*|CCB_PROJECT_VERSION=*|CCB_TEMPLATE_VERSION=*) key=${line%%=*}; value=${line#*=};; *) return 1;; esac
    case "$seen" in *" $key "*) return 1;; *) seen="$seen$key ";; esac
    case "$key" in CCB_PROJECT_NAME) PROJECT_NAME=$value;; CCB_PROJECT_PROFILE) PROJECT_PROFILE=$value;; esac
  done <"$project_file"
  [ -n "$PROJECT_NAME" ] && project_profile_id_is_safe "$PROJECT_PROFILE"
}
