#!/bin/sh
set -u
SCRIPT_DIR=$(CDPATH= cd "$(dirname "$0")" && pwd)
. "$SCRIPT_DIR/model-lib.sh"; . "$SCRIPT_DIR/project-config-lib.sh"; . "$SCRIPT_DIR/project-agents-lib.sh"; . "$SCRIPT_DIR/project-workflows-lib.sh"
usage() { echo 'usage: ccb.sh workflows [TARGET] | ccb.sh workflow show|plan NAME [TARGET] | ccb.sh workflow validate [TARGET]' >&2; exit "${1:-2}"; }
action=${1:-list}; case "$action" in list|show|plan|validate) :;; --help|-h) usage 0;; *) usage 2;; esac
if [ "$action" = show ] || [ "$action" = plan ]; then requested_name=${2:-}; project_workflow_name_is_safe "$requested_name" || { [ -n "$requested_name" ] && { echo "error: invalid workflow: $requested_name" >&2; exit 2; } || usage 2; }; target=${3:-.}; [ "$#" -le 3 ] || usage 2; else target=${2:-.}; [ "$#" -le 2 ] || usage 2; fi
[ -d "$target" ] && [ ! -L "$target" ] || { echo 'error: target is not a real directory' >&2; exit 1; }; target=$(CDPATH= cd "$target" && pwd) || exit 1
project_models_parse "$target/.ccb/models.conf" && project_agents_parse "$target/.ccb/agents.conf" || { echo 'error: invalid or missing project models or agents configuration' >&2; exit 1; }
project_workflows_parse "$target/.ccb/workflows.conf" || { echo '[WARN] Declarative workflows are not configured for this project' >&2; echo 'This project may have been created before V1.7.0-B' >&2; exit 1; }
if [ "$action" = validate ]; then echo '[OK] workflows.conf is valid'; echo '[OK] 4 workflows are configured'; printf '[OK] default workflow: %s\n' "$PROJECT_WORKFLOW_DEFAULT"; echo '[OK] all workflow steps reference declared agents'; echo '[OK] all workflow agents resolve to declared model roles'; echo '[INFO] workflow execution is disabled in V1.7.0-B'; echo '[INFO] access enforcement is declarative only'; exit 0; fi
if [ "$action" = list ]; then printf 'CCB Project Workflows\nTarget: %s\nSchema: %s\nDefault: %s\nExecution: disabled in V1.7.0-B\n\n%-10s %-36s %s\n' "$target" "$PROJECT_WORKFLOWS_VERSION" "$PROJECT_WORKFLOW_DEFAULT" WORKFLOW STEPS MODE; for name in feature bugfix design review; do project_workflow_details "$name"; case "$PROJECT_WORKFLOW_STEPS" in *developer*|*graphiste*) mode=includes-write;; *) mode=analysis-only;; esac; printf '%-10s %-36s %s\n' "$name" "$(printf '%s' "$PROJECT_WORKFLOW_STEPS" | sed 's/,/ -> /g')" "$mode"; done; exit 0; fi
project_workflow_details "$requested_name" || exit 1
case ",$PROJECT_WORKFLOW_NAMES," in *,"$requested_name",*) :;; *) echo "error: unknown workflow: $requested_name" >&2; echo "Available workflows: $PROJECT_WORKFLOW_NAMES" >&2; exit 1;; esac
if [ "$action" = show ]; then printf 'Workflow: %s\nDescription: %s\nDefault: %s\nExecution: disabled in V1.7.0-B\n' "$requested_name" "$PROJECT_WORKFLOW_DESCRIPTION" "$( [ "$requested_name" = "$PROJECT_WORKFLOW_DEFAULT" ] && printf yes || printf no)"; fi
count=0; readonly=0; writable=0; oldifs=$IFS; IFS=,; for role in $PROJECT_WORKFLOW_STEPS; do IFS=$oldifs; count=$((count + 1)); project_agent_details "$role"; model=$(project_agent_role_model_value "$role"); [ "$PROJECT_AGENT_ACCESS" = write ] && writable=$((writable + 1)) || readonly=$((readonly + 1)); if [ "$action" = plan ]; then [ "$count" -eq 1 ] && printf 'Workflow Plan\nName: %s\nDescription: %s\nTarget: %s\nSteps: %s\nExecution: disabled\n' "$requested_name" "$PROJECT_WORKFLOW_DESCRIPTION" "$target" "$(printf '%s' "$PROJECT_WORKFLOW_STEPS" | awk -F, '{print NF}')"; printf '\n%s. %s\n   Access: %s\n   Purpose: %s\n   Provider: %s\n   Model: %s\n' "$count" "$role" "$PROJECT_AGENT_ACCESS" "$PROJECT_AGENT_DESCRIPTION" "$PROJECT_MODEL_PROVIDER" "$model"; else printf '\nStep %s\n  Role: %s\n  Access: %s\n  Model role: %s\n  Provider: %s\n  Model: %s\n' "$count" "$role" "$PROJECT_AGENT_ACCESS" "$PROJECT_AGENT_MODEL_ROLE" "$PROJECT_MODEL_PROVIDER" "$model"; fi; IFS=,; done; IFS=$oldifs
if [ "$action" = plan ]; then printf '\nSummary:\n  Read-only steps: %s\n  Write-capable steps: %s\n  Enforcement: declarative only\n  No agents will be executed\n' "$readonly" "$writable"; else echo 'Enforcement: declarative only'; fi
