#!/bin/sh

run_id_is_valid() {
  value=$1
  case "$value" in *[!0-9a-z-]*|*..*|*--*|????????-??????-|????????-??????-*[!0-9a-z-]*|'') return 1;; esac
  date_part=${value%%-*}; rest=${value#*-}; time_part=${rest%%-*}; workflow=${rest#*-}
  [ "${#date_part}" -eq 8 ] && [ "${#time_part}" -eq 6 ] || return 1
  case "$workflow" in [a-z]|[a-z][a-z0-9-]* ) :;; *) return 1;; esac
}
run_status_is_valid() { case "$1" in pending|in-progress|blocked|completed|cancelled) return 0;; *) return 1;; esac; }
run_integer_is_valid() { case "$1" in ''|*[!0-9]*|0) return 1;; *) return 0;; esac; }
run_timestamp() { date '+%Y-%m-%dT%H:%M:%S%z'; }
run_identifier() { printf '%s-%s\n' "$(date '+%Y%m%d-%H%M%S')" "$1"; }
run_write_conf() { file=$1; temp=$(mktemp "$(dirname "$file")/.run.conf.tmp.XXXXXX") || return 1; printf 'CCB_RUN_VERSION=1\nCCB_RUN_ID=%s\nCCB_RUN_WORKFLOW=%s\nCCB_RUN_STATUS=%s\nCCB_RUN_CURRENT_STEP=%s\nCCB_RUN_STEP_COUNT=%s\nCCB_RUN_CREATED_AT=%s\nCCB_RUN_UPDATED_AT=%s\nCCB_RUN_COMPLETED_AT=\nCCB_RUN_SOURCE_TEMPLATE_VERSION=1.7.0\nCCB_RUN_SOURCE_WORKFLOWS_VERSION=1\nCCB_RUN_SOURCE_AGENTS_VERSION=1\nCCB_RUN_SOURCE_MODELS_VERSION=1\n' "$RUN_ID" "$RUN_WORKFLOW" "$RUN_STATUS" "$RUN_CURRENT" "$RUN_COUNT" "$RUN_CREATED" "$RUN_UPDATED" >"$temp" && chmod 644 "$temp" && mv "$temp" "$file"; }
run_parse_conf() { file=$1; [ -f "$file" ] && [ ! -L "$file" ] || return 1; RUN_ID= RUN_WORKFLOW= RUN_STATUS= RUN_CURRENT= RUN_COUNT= RUN_CREATED= RUN_UPDATED=; seen=' '; while IFS= read -r line || [ -n "$line" ]; do case "$line" in CCB_RUN_VERSION=1|CCB_RUN_SOURCE_TEMPLATE_VERSION=1.7.0|CCB_RUN_SOURCE_WORKFLOWS_VERSION=1|CCB_RUN_SOURCE_AGENTS_VERSION=1|CCB_RUN_SOURCE_MODELS_VERSION=1|CCB_RUN_COMPLETED_AT=) key=${line%%=*};; CCB_RUN_ID=*|CCB_RUN_WORKFLOW=*|CCB_RUN_STATUS=*|CCB_RUN_CURRENT_STEP=*|CCB_RUN_STEP_COUNT=*|CCB_RUN_CREATED_AT=*|CCB_RUN_UPDATED_AT=*) key=${line%%=*}; value=${line#*=};; *) return 1;; esac; case "$seen" in *" $key "*) return 1;; *) seen="$seen$key ";; esac; case "$key" in CCB_RUN_ID) RUN_ID=$value;; CCB_RUN_WORKFLOW) RUN_WORKFLOW=$value;; CCB_RUN_STATUS) RUN_STATUS=$value;; CCB_RUN_CURRENT_STEP) RUN_CURRENT=$value;; CCB_RUN_STEP_COUNT) RUN_COUNT=$value;; CCB_RUN_CREATED_AT) RUN_CREATED=$value;; CCB_RUN_UPDATED_AT) RUN_UPDATED=$value;; esac; done <"$file"; run_id_is_valid "$RUN_ID" && project_workflow_name_is_safe "$RUN_WORKFLOW" && run_status_is_valid "$RUN_STATUS" && run_integer_is_valid "$RUN_CURRENT" && run_integer_is_valid "$RUN_COUNT"; }
run_write_step() { dir=$1 number=$2 role=$3 status=$4; project_agent_details "$role"; model=$(project_agent_model_value "$PROJECT_AGENT_MODEL_ROLE") || return 1; printf 'CCB_STEP_VERSION=1\nCCB_STEP_NUMBER=%s\nCCB_STEP_ROLE=%s\nCCB_STEP_STATUS=%s\nCCB_STEP_ACCESS=%s\nCCB_STEP_MODEL_ROLE=%s\nCCB_STEP_PROVIDER=%s\nCCB_STEP_MODEL=%s\nCCB_STEP_DESCRIPTION=%s\nCCB_STEP_STARTED_AT=\nCCB_STEP_COMPLETED_AT=\n' "$number" "$role" "$status" "$PROJECT_AGENT_ACCESS" "$PROJECT_AGENT_MODEL_ROLE" "$PROJECT_MODEL_PROVIDER" "$model" "$PROJECT_AGENT_DESCRIPTION" >"$dir/step.conf"; }
run_step_parse() { file=$1; [ -f "$file" ] && [ ! -L "$file" ] || return 1; STEP_NUMBER= STEP_ROLE= STEP_STATUS= STEP_ACCESS= STEP_MODEL_ROLE= STEP_PROVIDER= STEP_MODEL= STEP_DESCRIPTION=; seen=' '; while IFS= read -r line || [ -n "$line" ]; do case "$line" in CCB_STEP_VERSION=1|CCB_STEP_STARTED_AT=|CCB_STEP_COMPLETED_AT=) key=${line%%=*};; CCB_STEP_NUMBER=*|CCB_STEP_ROLE=*|CCB_STEP_STATUS=*|CCB_STEP_ACCESS=*|CCB_STEP_MODEL_ROLE=*|CCB_STEP_PROVIDER=*|CCB_STEP_MODEL=*|CCB_STEP_DESCRIPTION=*) key=${line%%=*}; value=${line#*=};; *) return 1;; esac; case "$seen" in *" $key "*) return 1;; *) seen="$seen$key ";; esac; case "$key" in CCB_STEP_NUMBER) STEP_NUMBER=$value;; CCB_STEP_ROLE) STEP_ROLE=$value;; CCB_STEP_STATUS) STEP_STATUS=$value;; CCB_STEP_ACCESS) STEP_ACCESS=$value;; CCB_STEP_MODEL_ROLE) STEP_MODEL_ROLE=$value;; CCB_STEP_PROVIDER) STEP_PROVIDER=$value;; CCB_STEP_MODEL) STEP_MODEL=$value;; CCB_STEP_DESCRIPTION) STEP_DESCRIPTION=$value;; esac; done <"$file"; run_integer_is_valid "$STEP_NUMBER" && project_agent_role_is_safe "$STEP_ROLE" && case "$STEP_STATUS" in pending|ready|in-progress|completed|blocked|skipped) :;; *) return 1;; esac; project_agent_access_is_valid "$STEP_ACCESS" && project_agent_model_role_is_valid "$STEP_MODEL_ROLE" && [ -n "$STEP_PROVIDER" ] && [ -n "$STEP_MODEL" ] && [ -n "$STEP_DESCRIPTION" ]; }
run_validate_directory() { dir=$1; [ -d "$dir" ] && [ ! -L "$dir" ] || return 1; run_parse_conf "$dir/run.conf" || return 1; [ "$(basename "$dir")" = "$RUN_ID" ] || return 1; [ -f "$dir/context.md" ] && [ ! -L "$dir/context.md" ] || return 1; [ "$RUN_COUNT" -le 99 ] 2>/dev/null || return 1; i=1; while [ "$i" -le "$RUN_COUNT" ]; do matches=$(find "$dir" -maxdepth 1 -type d -name "$(printf '%02d' "$i")-*" ! -type l -print); [ "$(printf '%s\n' "$matches" | sed '/^$/d' | wc -l | tr -d ' ')" = 1 ] || return 1; stepdir=$matches; run_step_parse "$stepdir/step.conf" || return 1; [ "$STEP_NUMBER" = "$i" ] && [ "$(basename "$stepdir")" = "$(printf '%02d-%s' "$i" "$STEP_ROLE")" ] && [ -f "$stepdir/input.md" ] && [ ! -L "$stepdir/input.md" ] && [ -f "$stepdir/result.md" ] && [ ! -L "$stepdir/result.md" ] || return 1; i=$((i+1)); done; }
run_latest_id() { runs=$1; best=; bestkey=; for candidate in "$runs"/*; do [ -d "$candidate" ] && [ ! -L "$candidate" ] || continue; name=$(basename "$candidate"); run_id_is_valid "$name" || continue; key=$(printf '%s\n' "$name" | awk -F- '{suffix=1; if (NF>3) suffix=$NF; printf "%s%s%06d",$1,$2,suffix}'); if [ -z "$bestkey" ] || [ "$key" \> "$bestkey" ]; then best=$name; bestkey=$key; fi; done; [ -n "$best" ] && printf '%s\n' "$best"; }
